skore-io/culture

assets/style.css
dream-team.html

Adicionar minha descrição e adicionar efeito no hover dos elementos.

feat(pages): add ighor description

---

dream-team.html

adicionando minhas informações

feat(dream_team): ciro page description

---

dream-team.html

Adicionado card com dados do Oscar :)

feat(dream_team): oscar silva description

---

dream-team.html

Adicionando minha descriçãozinha pois quero fazer parte do dream team :)

feat(dream_team): gabi khoury description

---

dream-team.html

Adicionado minhas informações.

feat(dream_team): add andre description

---

dream-team.html

feat(dream_team): add renato fields profile

---

dream-team.html

Adicionando meu perfil ao dream-team
Porque sou novo integrante na squad

feat: add batini profile

---

dream-team.html

Ajustando imagem do perfil e movendo para o time de Engenharia
Imagem estava quebrada e o perfil ficou no time errado, de Produto

fix: adjusting image batini profile

---

dream-team.html

Ajustando estilização da página do dream-team
PR passado subiu com quebra de estilização, fiz a correção

fix adjusting stylization

---

dream-team.html

- Remove a Sabrine do time;
Não sei meu Deus!! Não queria ter que fazer issooo!!!!
#voltaSabrine

feat: remove sabrine

---

dream-team/team-operation.js

Adicionando o perfil do Larson ao Dream Team.
Porque ele faz parte do Dream Team, mas não possui Github.

docs(dream_team): add larson's profile

---

dream-team/team-operation.js

Corrigindo os espaçamentos na descrição.
Acredito que seja a causa de a seção de Operações ter quebrado :D

docs(dream_team): update larson's profile

---

dream-team/team-operation.js

Inclusão de bio na page Dream Page.
A minha bio ainda não tinha sido preenchida.

inclusao de bio na page dream team

---

dream-team/team-product.js

Inclusão de bio da Luiza Sernizon na page dream team
Ela estava sem bio cadastrada na page

inclusao de bio da luiza sernizon na page dream team

---

dream-team/team-data.js

Adicionando o perfil do @bernardesls ao dream team.
Porque ele faz parte do time :)

docs(dream_team): add lucas' profile

---

dream-team/team-data.js

adicionando meu perfil ao dream team
porque a Gabi pediu

docs(dream_team): add gyovana-profile

---

dream-team/team-product.js
dream-team/util.js

Adicionando perfil do Thiago Cassimiro ao Dream Team.
🚀

docs(dream_team): add cassimiro-profile

---

dream-team/team-dev.js

Adicionando meu perfil ao Dream Team.

docs(dream_team): add rodrigobatini profile

---

dream-team/team-dev.js

Removendo meu perfil do Oziel do Dream Team.
Meu último PR 😢

docs(dream_team): remove Oziel profile

---

dream-team/team-dev.js

Adicionando informação sobre o novo engenheiro de software do time, Pedro Rasera.
Porque o Guilherme falou que é parte do meu onboarding :D

feat(dev-team): added info about Pedro Rasera

---

docs/dream-team.md
dream-team/team-product.js

Adicionando o perfil do Fabrizio.
Nosso GPM 🚀

docs(dream_team): add fabrizio profile

---

dream-team/team-dev.js
dream-team/team-product.js

Adicionando o perfil do Giovanni Attina.
PM do time de Conteúdo  🚀

docs(dream_team): add giovanni profile

---

dream-team/team-dev.js

Adicionando meu perfil ao Dream Team.

docs(dream_team): add Fabio Junior da Silva profile.

---

README.md

Adiciona URL com as informações compiladas e renderizadas
Facilitar acesso às informações sem precisar subir a aplicação localmente

docs: add website with compiled info

---

dream-team/team-dev.js

Adicionando meu perfil ao Dream Team

docs(dream_team): add jeferson nascimento profile.

---

dream-team/team-dev.js

Adicionando meu perfil ao Dream Team.

docs(dream_team): add Dominic profile

---

dream-team/team-dev.js

Ajustando formatação e fluidez do texto
Isso vai melhorar o entendimento de quem ler.

docs(dream_team): improve Dominic profile

---

Gemfile.lock
dream-team/team-dev.js

What?
Adicionando meu perfil ao Dream Team
Why?

docs: thiago profile

---

dream-team/team-data.js

Adicionando o perfil do @Keven ao Dream Team.
Novo membro do time de dados 🚀

docs(dream_team): add keven profile

---

dream-team/team-ux.js

Adicionando Luciana na seção de Design
Membro essencial da nossa estrutura e não estava lá!! haha

docs(dream_team): adding Luciana as ux

---

dream-team/team-data.js

Adicionando meu perfil ao Dream Team.

docs(dream_team): add {Luiz Iavarone} profile

---

dream-team/team-dev.js

Adicionado o perfil de thiago cacio no time de desenvolvedores.
Incrementar o time e entender os padrões de commits e PRs

docs(dream_team): Add Thiago Cacio profile to dream Team
